# Copyright (c) 2026 NumFast
# SPDX-License-Identifier: AGPL-3.0-only
name = "Fused"
version = "0.1.0"
depends = []
alias = ["fused_build", "fused_run", "fused_source", "fused_oracle"]
mods = ["fused_build", "fused_run", "fused_source", "fused_oracle"]

[metadata]
level = "compute"
