name = "Storage"
version = "0.1.0"
depends = []
alias = [
    "storage",
    "table", "column", "compute_plan", "optimize_table",
    "column_layout", "packing_plan",
    "Table", "Column", "ColumnType", "PackingPlan", "ColumnLayout"
]
mods = [
    "storage",
    "table", "column", "compute_plan", "optimize_table",
    "column_layout", "packing_plan",
    "Table", "Column", "ColumnType", "PackingPlan", "ColumnLayout"
]

[metadata]
description = "P0-S dzst ALL rows"
