name = "Storage"
version = "1.0.0"
depends = []
alias = [
    "table", "column", "compute_plan", "optimize_table",
    "column_layout", "packing_plan",
    "Table", "Column", "ColumnType", "PackingPlan", "ColumnLayout"
]
mods = [
    "table", "column", "compute_plan", "optimize_table",
    "column_layout", "packing_plan",
    "Table", "Column", "ColumnType", "PackingPlan", "ColumnLayout"
]

[metadata]
description = "Storage layer: Column, PackingPlan, Table, Optimize"
