# Copyright (c) 2026 NumFast
# SPDX-License-Identifier: AGPL-3.0-only
name = "Runtime"
version = "0.1.0"
depends = ["Planner", "CPU", "GPU"]
alias = ["evaluate"]
mods = ["evaluate"]

[metadata]
level = "runtime"
