# Copyright (c) 2026 NumFast
# SPDX-License-Identifier: AGPL-3.0-only
name = "Core"
version = "0.1.0"
depends = []
alias = ["canonical_dtype", "accum_dtype", "is_scaled", "check_overflow", "check_int32_range", "format_error"]
mods = ["canonical_dtype", "accum_dtype", "is_scaled", "check_overflow", "check_int32_range", "format_error"]

[metadata]
level = "global"
