// Packing WGSL — generated by generate_pack_shader(layout)
// P0-S dzst ALL rows, 6 inputs, workgroup 1024, Config low_offset,n, parts mask/shift
// Canonical template: copy of develop/backtest/Loaders/_lib/pack_shader_gen.py adapted for PackingPlan

struct Config { low_offset: i32, n: u32, }
@group(0) @binding(0) var<storage, read> low: array<i32>;
@group(0) @binding(1) var<storage, read> d_open: array<i32>;
@group(0) @binding(2) var<storage, read> d_high: array<i32>;
@group(0) @binding(3) var<storage, read> d_close: array<i32>;
@group(0) @binding(4) var<storage, read> buy_vol: array<u32>;
@group(0) @binding(5) var<storage, read> sell_vol: array<u32>;
@group(0) @binding(6) var<uniform> config: Config;
@group(0) @binding(7) var<storage, read_write> out: array<u32>;

@compute @workgroup_size(1024)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
    let i = gid.x;
    if (i >= config.n) { return; }
    let lo = u32(low[i] - config.low_offset);
    let dO = u32(d_open[i]);
    let dH = u32(d_high[i]);
    let dC = u32(d_close[i]);
    let bv = buy_vol[i];
    let sv = sell_vol[i];
    // --- begin generated parts (example for 6x 32-bit columns => 6 parts) ---
    // This static template illustrates the packing logic. The actual shader is
    // generated at runtime by generate_pack_shader(layout) which computes
    // per-column mask/shift based on layout.columns[*].parts.
    // Example: num_parts = 6, each column 32 bits, no cross-boundary.
    var p0: u32 = 0u;
    var p1: u32 = 0u;
    var p2: u32 = 0u;
    var p3: u32 = 0u;
    var p4: u32 = 0u;
    var p5: u32 = 0u;
    // low (32 bits) -> p0: (lo & 0xFFFFFFFFu)
    p0 |= (lo & 0xFFFFFFFFu);
    // d_open (32 bits) -> p1
    p1 |= (dO & 0xFFFFFFFFu);
    // d_high (32 bits) -> p2
    p2 |= (dH & 0xFFFFFFFFu);
    // d_close (32 bits) -> p3
    p3 |= (dC & 0xFFFFFFFFu);
    // buy_vol (32 bits) -> p4
    p4 |= (bv & 0xFFFFFFFFu);
    // sell_vol (32 bits) -> p5
    p5 |= (sv & 0xFFFFFFFFu);
    // --- with cross-boundary, example uses mask/shift: ---
    // p0 |= ((lo >> 16u) & 0xFFFFu);
    // p0 |= ((lo & 0xFFFFu) << 0u);
    // p1 |= ((dO >> 8u) & 0xFFu) << 16u  etc.
    out[i * 6u + 0u] = p0;
    out[i * 6u + 1u] = p1;
    out[i * 6u + 2u] = p2;
    out[i * 6u + 3u] = p3;
    out[i * 6u + 4u] = p4;
    out[i * 6u + 5u] = p5;
}
