# Copyright (c) 2026 NumFast
# SPDX-License-Identifier: AGPL-3.0-only
name = "CPU"
version = "0.1.0"
depends = ["Core", "GroupedHash"]
alias = ["cpu_execute", "cpu_capability"]
mods = ["cpu_execute", "cpu_capability"]

[metadata]
level = "driver"
